## DataSource Config
#logging:
#  level:



spring:
  application:
    name: mybatis-plus-test  # 你的服务名（注册到 Nacos 的名称）
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848  # Nacos 服务器地址（如果是远程，替换为实际 IP）
      config:
        server-addr: localhost:8848  # Nacos 配置中心地址（如果使用配置中心）
        file-extension: yml         # 配置文件格式（如 yaml、properties）
        namespace: public            # 命名空间（默认 public）
        group: DEFAULT_GROUP         # 分组（默认 DEFAULT_GROUP）
