version: '3.8'

name: rag-res
services:
  mysql:
    image: docker.m.daocloud.io/mysql:latest  # 修改镜像源
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    ports:
      - "3306:3306"
  # XXL-JOB 调度中心（Admin）
  xxl-job-admin:
    image: xuxueli/xxl-job-admin:2.4.0  # 使用最新稳定版
    container_name: xxl-job-admin
    environment:
      - PARAMS=--spring.datasource.url=jdbc:mysql://mysql:3306/xxl_job?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai --spring.datasource.username=root --spring.datasource.password=123456
    ports:
      - "8081:8080"  # 访问端口
    depends_on:
      - mysql  # 确保 MySQL 先启动

  nacos:
    image: docker.m.daocloud.io/nacos/nacos-server:v2.2.3  # 使用 DaoCloud 镜像源加速拉取
    container_name: rag-res-nacos
    environment:
      - NACOS_AUTH_IDENTITY_KEY=2222
      - NACOS_AUTH_IDENTITY_VALUE=2xxx
      - NACOS_AUTH_TOKEN=VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=
      - PREFER_HOST_MODE=hostname
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MODE=standalone  # 单机模式
      - MYSQL_SERVICE_HOST=mysql  # 指定 MySQL 地址（与 Docker 服务名一致）
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=123456
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
      - MYSQL_SERVICE_DB_NAME=nacos  # 指定数据库名称，需提前在 MySQL 创建



    ports:
      - "8080:8080"
      - "8848:8848"  # Nacos 控制台访问端口
      - "9848:9848"
    depends_on:
      - mysql  # 确保 MySQL 先启动


  minio:
    image: docker.m.daocloud.io/minio/minio  # 修改镜像源
    container_name: rag-res-minio
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Shens@12345
    ports:
      - "9000:9000"
      - "9001:9001"
    command: server /data --console-address ":9001"


  es:
    image: docker.m.daocloud.io/elasticsearch:8.12.0  # 修改镜像源
    container_name: rag-res-es
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: single-node
      network.host: 0.0.0.0   # 新增此行！
      HTTP_PORT: 9200
        # 禁用 SSL（防止意外启用 HTTPS）
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
      xpack.security.transport.ssl.enabled: "false"
      xpack.security.http.ssl.verification_mode: "none"
    ports:
      - "9200:9200"
    command: bash -c "if [ ! -d \"$ES_HOME/plugins/analysis-ik\" ]; then elasticsearch-plugin install --batch https://release.infinilabs.com/analysis-ik/stable/elasticsearch-analysis-ik-8.12.0.zip; fi && elasticsearch"
